#include <iostream>
#include <vector>
#include <string>
#include <unordered_map>
#include <algorithm>

using namespace std;

class Solution 
{
public:
	vector<int> findAnagrams(string s, string p) 
	{
		vector<int> result;

		if (p.length() > s.length())
			return result;

		vector<int> map(26);

		for_each(p.begin(), p.end(), [&map](char element) {
			map[element - 'a']++;
		});

		int running = 0;

		while (running <= s.length() - p.length())
		{
			if (map[s[running] - 'a'] == 0)
			{
				running++;
				continue;
			}

			bool found = true;
			vector<int> map2 = map;
		
			for (int i = 0; i < p.length(); i++)
			{
				if (map2[s[running + i] - 'a'])
				{
					map2[s[running + i] - 'a']--;
					continue;
				}

				found = false;
				break;
			}

			if (found)
				result.push_back(running);

			running++;
		}

		return result;
	}
};

int main()
{
	Solution s;
	vector<int> res = s.findAnagrams("xnaugzecytkijqovfmhdrspwblxnaugzecytkijqovfmhdrspwblxnaugzecytkijqovfmhdrspwblxnaugzecytkijqovfmhdrspwblxnaugzecytkijqovfmhdrspwblxnaugzecytkijqovfmhdrspwblxnaugzecytkijqovfmhdrspwblxnaugzecytkijqovfmhdrspwblxnaugzecytkijqovfmhdrspwblxnaugzecytkijqovfmhdrspwblxnaugzecytkijqovfmhdrspwblxnaugzecytkijqovfmhdrspwblxnaugzecytkijqovfmhdrspwblxnaugzecytkijqovfmhdrspwblxnaugzecytkijqovfmhdrspwblxnaugzecytkijqovfmhdrspwblxnaugzecytkijqovfmhdrspwblxnaugzecytkijqovfmhdrspwblxnaugzecytkijqovfmhdrspwblxnaugzecytkijqovfmhdrspwblxnaugzecytkijqovfmhdrspwblxnaugzecytkijqovfmhdrspwblxnaugzecytkijqovfmhdrspwblxnaugzecytkijqovfmhdrspwblxnaugzecytkijqovfmhdrspwblxnaugzecytkijqovfmhdrspwblxnaugzecytkijqovfmhdrspwblxnaugzecytkijqovfmhdrspwblxnaugzecytkijqovfmhdrspwblxnaugzecytkijqovfmhdrspwblxnaugzecytkijqovfmhdrspwblxnaugzecytkijqovfmhdrspwblxnaugzecytkijqovfmhdrspwblxnaugzecytkijqovfmhdrspwblxnaugzecytkijqovfmhdrspwblxnaugzecytkijqovfmhdrspwblxnaugzecytkijqovfmhdrspwblxnaugzecytkijqovfmhdrspwblxnaugzecytkijqovfmhdrspwblxnaugzecytkijqovfmhdrspwblxnaugzecytkijqovfmhdrspwblxnaugzecytkijqovfmhdrspwblxnaugzecytkijqovfmhdrspwblxnaugzecytkijqovfmhdrspwblxnaugzecytkijqovfmhdrspwblxnaugzecytkijqovfmhdrspwblxnaugzecytkijqovfmhdrspwblxnaugzecytkijqovfmhdrspwblxnaugzecytkijqovfmhdrspwblxnaugzecytkijqovfmhdrspwblxnaugzecytkijqovfmhdrspwblxnaugzecytkijqovfmhdrspwblxnaugzecytkijqovfmhdrspwblxnaugzecytkijqovfmhdrspwblxnaugzecytkijqovfmhdrspwblxnaugzecytkijqovfmhdrspwblxnaugzecytkijqovfmhdrspwblxnaugzecytkijqovfmhdrspwblxnaugzecytkijqovfmhdrspwblxnaugzecytkijqovfmhdrspwblxnaugzecytkijqovfmhdrspwblxnaugzecytkijqovfmhdrspwblxnaugzecytkijqovfmhdrspwblxnaugzecytkijqovfmhdrspwblxnaugzecytkijqovfmhdrspwblxnaugzecytkijqovfmhdrspwblxnaugzecytkijqovfmhdrspwblxnaugzecytkijqovfmhdrspwblxnaugzecytkijqovfmhdrspwblxnaugzecytkijqovfmhdrspwblxnaugzecytkijqovfmhdrspwblxnaugzecytkijqovfmhdrspwblxnaugzecytkijqovfmhdrspwblxnaugzecytkijqovfmhdrspwblxnaugzecytkijqovfmhdrspwblxnaugzecytkijqovfmhdrspwblxnaugzecytkijqovfmhdrspwblxnaugzecytkijqovfmhdrspwblxnaugzecytkijqovfmhdrspwblxnaugzecytkijqovfmhdrspwblxnaugzecytkijqovfmhdrspwblxnaugzecytkijqovfmhdrspwblxnaugzecytkijqovfmhdrspwblxnaugzecytkijqovfmhdrspwblxnaugzecytkijqovfmhdrspwblxnaugzecytkijqovfmhdrspwblxnaugzecytkijqovfmhdrspwblxnaugzecytkijqovfmhdrspwblxnaugzecytkijqovfmhdrspwblxnaugzecytkijqovfmhdrspwblxnaugzecytkijqovfmhdrspwblxnaugzecytkijqovfmhdrspwblxnaugzecytkijqovfmhdrspwblxnaugzecytkijqovfmhdrspwblxnaugzecytkijqovfmhdrspwblxnaugzecytkijqovfmhdrspwblxnaugzecytkijqovfmhdrspwblxnaugzecytkijqovfmhdrspwblxnaugzecytkijqovfmhdrspwblxnaugzecytkijqovfmhdrspwblxnaugzecytkijqovfmhdrspwblxnaugzecytkijqovfmhdrspwblxnaugzecytkijqovfmhdrspwblxnaugzecytkijqovfmhdrspwblxnaugzecytkijqovfmhdrspwblxnaugzecytkijqovfmhdrspwblxnaugzecytkijqovfmhdrspwblxnaugzecytkijqovfmhdrspwblxnaugzecytkijqovfmhdrspwblxnaugzecytkijqovfmhdrspwblxnaugzecytkijqovfmhdrspwblxnaugzecytkijqovfmhdrspwblxnaugzecytkijqovfmhdrspwblxnaugzecytkijqovfmhdrspwblxnaugzecytkijqovfmhdrspwblxnaugzecytkijqovfmhdrspwblxnaugzecytkijqovfmhdrspwblxnaugzecytkijqovfmhdrspwblxnaugzecytkijqovfmhdrspwblxnaugzecytkijqovfmhdrspwblxnaugzecytkijqovfmhdrspwblxnaugzecytkijqovfmhdrspwblxnaugzecytkijqovfmhdrspwblxnaugzecytkijqovfmhdrspwblxnaugzecytkijqovfmhdrspwblxnaugzecytkijqovfmhdrspwblxnaugzecytkijqovfmhdrspwblxnaugzecytkijqovfmhdrspwblxnaugzecytkijqovfmhdrspwblxnaugzecytkijqovfmhdrspwblxnaugzecytkijqovfmhdrspwblxnaugzecytkijqovfmhdrspwblxnaugzecytkijqovfmhdrspwblxnaugzecytkijqovfmhdrspwblxnaugzecytkijqovfmhdrspwblxnaugzecytkijqovfmhdrspwblxnaugzecytkijqovfmhdrspwblxnaugzecytkijqovfmhdrspwblxnaugzecytkijqovfmhdrspwblxnaugzecytkijqovfmhdrspwblxnaugzecytkijqovfmhdrspwblxnaugzecytkijqovfmhdrspwblxnaugzecytkijqovfmhdrspwblxnaugzecytkijqovfmhdrspwblxnaugzecytkijqovfmhdrspwblxnaugzecytkijqovfmhdrspwblxnaugzecytkijqovfmhdrspwblxnaugzecytkijqovfmhdrspwblxnaugzecytkijqovfmhdrspwblxnaugzecytkijqovfmhdrspwblxnaugzecytkijqovfmhdrspwblxnaugzecytkijqovfmhdrspwblxnaugzecytkijqovfmhdrspwblxnaugzecytkijqovfmhdrspwblxnaugzecytkijqovfmhdrspwblxnaugzecytkijqovfmhdrspwblxnaugzecytkijqovfmhdrspwblxnaugzecytkijqovfmhdrspwblxnaugzecytkijqovfmhdrspwblxnaugzecytkijqovfmhdrspwblxnaugzecytkijqovfmhdrspwblxnaugzecytkijqovfmhdrspwblxnaugzecytkijqovfmhdrspwblxnaugzecytkijqovfmhdrspwblxnaugzecytkijqovfmhdrspwblxnaugzecytkijqovfmhdrspwblxnaugzecytkijqovfmhdrspwblxnaugzecytkijqovfmhdrspwblxnaugzecytkijqovfmhdrspwblxnaugzecytkijqovfmhdrspwblxnaugzecytkijqovfmhdrspwblxnaugzecytkijqovfmhdrspwblxnaugzecytkijqovfmhdrspwblxnaugzecytkijqovfmhdrspwblxnaugzecytkijqovfmhdrspwblxnaugzecytkijqovfmhdrspwblxnaugzecytkijqovfmhdrspwblxnaugzecytkijqovfmhdrspwblxnaugzecytkijqovfmhdrspwblxnaugzecytkijqovfmhdrspwblxnaugzecytkijqovfmhdrspwblxnaugzecytkijqovfmhdrspwblxnaugzecytkijqovfmhdrspwblxnaugzecytkijqovfmhdrspwblxnaugzecytkijqovfmhdrspwblxnaugzecytkijqovfmhdrspwblxnaugzecytkijqovfmhdrspwblxnaugzecytkijqovfmhdrspwblxnaugzecytkijqovfmhdrspwblxnaugzecytkijqovfmhdrspwblxnaugzecytkijqovfmhdrspwblxnaugzecytkijqovfmhdrspwblxnaugzecytkijqovfmhdrspwblxnaugzecytkijqovfmhdrspwblxnaugzecytkijqovfmhdrspwblxnaugzecytkijqovfmhdrspwblxnaugzecytkijqovfmhdrspwblxnaugzecytkijqovfmhdrspwblxnaugzecytkijqovfmhdrspwblxnaugzecytkijqovfmhdrspwblxnaugzecytkijqovfmhdrspwblxnaugzecytkijqovfmhdrspwblxnaugzecytkijqovfmhdrspwblxnaugzecytkijqovfmhdrspwblxnaugzecytkijqovfmhdrspwblxnaugzecytkijqovfmhdrspwblxnaugzecytkijqovfmhdrspwblxnaugzecytkijqovfmhdrspwblxnaugzecytkijqovfmhdrspwblxnaugzecytkijqovfmhdrspwblxnaugzecytkijqovfmhdrspwblxnaugzecytkijqovfmhdrspwblxnaugzecytkijqovfmhdrspwblxnaugzecytkijqovfmhdrspwblxnaugzecytkijqovfmhdrspwblxnaugzecytkijqovfmhdrspwblxnaugzecytkijqovfmhdrspwblxnaugzecytkijqovfmhdrspwblxnaugzecytkijqovfmhdrspwblxnaugzecytkijqovfmhdrspwblxnaugzecytkijqovfmhdrspwblxnaugzecytkijqovfmhdrspwblxnaugzecytkijqovfmhdrspwblxnaugzecytkijqovfmhdrspwblxnaugzecytkijqovfmhdrspwblxnaugzecytkijqovfmhdrspwblxnaugzecytkijqovfmhdrspwblxnaugzecytkijqovfmhdrspwblxnaugzecytkijqovfmhdrspwblxnaugzecytkijqovfmhdrspwblxnaugzecytkijqovfmhdrspwblxnaugzecytkijqovfmhdrspwblxnaugzecytkijqovfmhdrspwblxnaugzecytkijqovfmhdrspwblxnaugzecytkijqovfmhdrspwblxnaugzecytkijqovfmhdrspwblxnaugzecytkijqovfmhdrspwblxnaugzecytkijqovfmhdrspwblxnaugzecytkijqovfmhdrspwblxnaugzecytkijqovfmhdrspwblxnaugzecytkijqovfmhdrspwblxnaugzecytkijqovfmhdrspwblxnaugzecytkijqovfmhdrspwblxnaugzecytkijqovfmhdrspwblxnaugzecytkijqovfmhdrspwblxnaugzecytkijqovfmhdrspwblxnaugzecytkijqovfmhdrspwblxnaugzecytkijqovfmhdrspwblxnaugzecytkijqovfmhdrspwblxnaugzecytkijqovfmhdrspwblxnaugzecytkijqovfmhdrspwblxnaugzecytkijqovfmhdrspwblxnaugzecytkijqovfmhdrspwblxnaugzecytkijqovfmhdrspwblxnaugzecytkijqovfmhdrspwblxnaugzecytkijqovfmhdrspwblxnaugzecytkijqovfmhdrspwblxnaugzecytkijqovfmhdrspwblxnaugzecytkijqovfmhdrspwblxnaugzecytkijqovfmhdrspwblxnaugzecytkijqovfmhdrspwblxnaugzecytkijqovfmhdrspwblxnaugzecytkijqovfmhdrspwblxnaugzecytkijqovfmhdrspwblxnaugzecytkijqovfmhdrspwblxnaugzecytkijqovfmhdrspwblxnaugzecytkijqovfmhdrspwblxnaugzecytkijqovfmhdrspwblxnaugzecytkijqovfmhdrspwblxnaugzecytkijqovfmhdrspwblxnaugzecytkijqovfmhdrspwblxnaugzecytkijqovfmhdrspwblxnaugzecytkijqovfmhdrspwblxnaugzecytkijqovfmhdrspwblxnaugzecytkijqovfmhdrspwblxnaugzecytkijqovfmhdrspwblxnaugzecytkijqovfmhdrspwblxnaugzecytkijqovfmhdrspwblxnaugzecytkijqovfmhdrspwblxnaugzecytkijqovfmhdrspwblxnaugzecytkijqovfmhdrspwblxnaugzecytkijqovfmhdrspwblxnaugzecytkijqovfmhdrspwblxnaugzecytkijqovfmhdrspwblxnaugzecytkijqovfmhdrspwblxnaugzecytkijqovfmhdrspwblxnaugzecytkijqovfmhdrspwblxnaugzecytkijqovfmhdrspwblxnaugzecytkijqovfmhdrspwblxnaugzecytkijqovfmhdrspwblxnaugzecytkijqovfmhdrspwblxnaugzecytkijqovfmhdrspwblxnaugzecytkijqovfmhdrspwblxnaugzecytkijqovfmhdrspwblxnaugzecytkijqovfmhdrspwblxnaugzecytkijqovfmhdrspwblxnaugzecytkijqovfmhdrspwblxnaugzecytkijqovfmhdrspwblxnaugzecytkijqovfmhdrspwblxnaugzecytkijqovfmhdrspwbl",
		"kijqovfmhdrspwbl");
	return 0;
}